import type { PhotoCardData } from '@coffic/cosy-ui/vue';

// 简单示例数据
export const simplePhotos: PhotoCardData[] = [
    {
        id: '1',
        src: 'https://picsum.photos/300/200?random=1',
        alt: '示例图片 1',
        size: 'md',
        shape: 'square',
        style: 'default',
    },
    {
        id: '2',
        src: 'https://picsum.photos/300/200?random=2',
        alt: '示例图片 2',
        size: 'lg',
        shape: 'rectangle',
        style: 'default',
    },
    {
        id: '3',
        src: 'https://picsum.photos/300/200?random=3',
        alt: '示例图片 3',
        size: 'md',
        shape: 'square',
        style: 'default',
    },
    {
        id: '4',
        src: 'https://picsum.photos/300/200?random=4',
        alt: '示例图片 4',
        size: 'sm',
        shape: 'square',
        style: 'default',
    },
    {
        id: '5',
        src: 'https://picsum.photos/300/200?random=5',
        alt: '示例图片 5',
        size: 'md',
        shape: 'rectangle',
        style: 'default',
    },
    {
        id: '6',
        src: 'https://picsum.photos/300/200?random=6',
        alt: '示例图片 6',
        size: 'lg',
        shape: 'square',
        style: 'default',
    },
];

// 照片墙示例数据
export const photoWallPhotos: PhotoCardData[] = [
    {
        id: 'photo-1',
        src: 'https://picsum.photos/400/300?random=10',
        alt: '照片墙图片 1',
        size: 'lg',
        shape: 'rectangle',
        style: 'default',
    },
    {
        id: 'photo-2',
        src: 'https://picsum.photos/200/200?random=11',
        alt: '照片墙图片 2',
        size: 'md',
        shape: 'square',
        style: 'default',
    },
    {
        id: 'photo-3',
        src: 'https://picsum.photos/300/200?random=12',
        alt: '照片墙图片 3',
        size: 'md',
        shape: 'rectangle',
        style: 'default',
    },
    {
        id: 'photo-4',
        src: 'https://picsum.photos/200/200?random=13',
        alt: '照片墙图片 4',
        size: 'sm',
        shape: 'square',
        style: 'default',
    },
    {
        id: 'photo-5',
        src: 'https://picsum.photos/400/200?random=14',
        alt: '照片墙图片 5',
        size: 'lg',
        shape: 'wide',
        style: 'default',
    },
    {
        id: 'photo-6',
        src: 'https://picsum.photos/200/300?random=15',
        alt: '照片墙图片 6',
        size: 'md',
        shape: 'tall',
        style: 'default',
    },
    {
        id: 'photo-7',
        src: 'https://picsum.photos/200/200?random=16',
        alt: '照片墙图片 7',
        size: 'sm',
        shape: 'square',
        style: 'default',
    },
    {
        id: 'photo-8',
        src: 'https://picsum.photos/300/200?random=17',
        alt: '照片墙图片 8',
        size: 'md',
        shape: 'rectangle',
        style: 'default',
    },
];
